---
- name: Deploy Python Flask App
  hosts: "{{ target_server }}"
  become: yes  # Run tasks with sudo privileges
  vars:
    app_directory: /app  # Set the path to your app directory
  tasks:
    - name: Ensure the app directory exists
      file:
        path: "{{ app_directory }}"
        state: directory
        recurse: yes

    - name: Install Python
      yum:
        name: python3
        state: present

    - name: Copy app files to the server
      synchronize:
        src: ./  # Source directory, assumes the playbook and app files are in the same directory
        dest: "{{ app_directory }}"
        recursive: yes
      notify:
        - Restart Flask App

    - name: Install Python dependencies
      pip:
        requirements: "{{ app_directory }}/requirements.txt"

    - name: Copy and enable systemd service file
      template:
        src: flask-app.service.j2  # Template file
        dest: /etc/systemd/system/flask-app.service

    - name: Start and enable the Flask app service
      systemd:
        name: flask-app
        enabled: yes
        state: started
        daemon_reload: yes

  handlers:
    - name: Restart Flask App
      systemd:
        name: flask-app
        state: restarted
      ignore_errors: yes

