name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python3 test_app.py

      - name: Setup ssh
        shell: bash
        run: |
          eval `ssh-agent -s`
          mkdir -p ~/.ssh/
          touch ~/.ssh/id_rsa
          echo -e "${{secrets.SSH_SECRET_KEY}}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -t rsa,dsa,ecdsa,ed25519 ${{secrets.TEST_SERVER_IP}} >> /home/runner/.ssh/known_hosts
          ssh-keyscan -t rsa,dsa,ecdsa,ed25519 ${{secrets.PROD_SERVER_IP}} >> /home/runner/.ssh/known_hosts

      - name: Deploy to test server
        shell: bash
        run: |
          ansible-playbook deploy-playbook.yml -e "ansible_host=${{secrets.TEST_SERVER_IP}}"
          echo "Performing test healthcheck"
          curl ${{ secrets.TEST_SERVER_IP }}

      - name: Deploy to prod server
        shell: bash
        run: |
          ansible-playbook deploy-playbook.yml -e "ansible_host=${{secrets.PROD_SERVER_IP}}"
          echo "Performing prod healthcheck"
          curl ${{ secrets.PROD_SERVER_IP }}